dist: trusty
sudo: required
language: php
php:
  - 7.2
  - 7.3

env:
  global:
    - CORE_BRANCH=master

branches:
  only:
    - master
    - /^stable\d+(\.\d+)?$/

before_install:
  - wget https://raw.githubusercontent.com/nextcloud/travis_ci/master/before_install.sh
  - bash ./before_install.sh survey_server $CORE_BRANCH $DB

script:
  # Test the app
  - sh -c "if [ '$CODECHECK' = '1' ]; then find . -name \*.php -exec php -l \"{}\" \;; fi"
  - cd ../../
  - sh -c "if [ '$CODECHECK' = '1' ]; then ./occ app:check-code $APP_NAME -c private -c strong-comparison; fi"
  - sh -c "if [ '$CODECHECK' = '2' ]; then ./occ app:check-code $APP_NAME -c deprecation; fi"
  - cd apps/$APP_NAME/

  # Run phpunit tests
  - cd tests/unit
  - sh -c "if [ '$CODECHECK' != '1' -a '$CODECHECK' != '2' ]; then phpunit --configuration phpunit.xml; fi"

matrix:
  include:
    - php: 7.2
      env: DB=sqlite
    - php: 7.3
      env: DB=sqlite
    - php: 7.2
      env: DB=sqlite;CODECHECK=1
    - php: 7.2
      env: DB=sqlite;CODECHECK=2
  fast_finish: true
